import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import {
  Card,
  Button,
  Box,
  Grid,
  Center,
} from "@mantine/core";
import { DatePicker } from "@mantine/dates";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>When Can We Do</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="h-screen">
        <Box className="w-full h-full flex justify-center content-center flex-wrap">
          <Card
            shadow="sm"
            p="lg"
            radius="md"
            withBorder
            className="w-96 min-h-96 pt-[14px]"
          >
            <Grid columns={7} gutter={0}>
              <Grid.Col span={7} className="text-4xl text-center mb-5 mt-10">
                When Can We Do?
              </Grid.Col>
              <Grid.Col span={7} className="text-2xl text-center mb-8">
                Where all tasks come<br></br> to get done
              </Grid.Col>
              <Grid.Col span={7} className="mb-10">
                <Link href="/calendar">
                  <Center>
                    {/* <Button
                      type="submit"
                      variant="gradient"
                      gradient={{ from: "#045DE9", to: "#09C6F9", deg: 35 }}
                      className="color align-center text-lg"
                    >
                      Sign In
                    </Button> */}
                    <Link href="/calendar">
                      <Button>
                        Calendar View
                      </Button>
                    </Link>
                    <Link href="/list">
                      <Button>
                        List View
                      </Button>
                    </Link>
                  </Center>
                </Link>
              </Grid.Col>
            </Grid>
          </Card>
        </Box>
      </Box>
    </>
  );
}
